de = {
    "group_lang": {
        "set": "Deutsch: An",
        "inv": "Ungültige Sprachoption.",
        "message_1": "Deutsch: An",
        "message_2": "Deutsch ist bereits aktiviert.",
        "message_3": "Nur Admins können die Sprache ändern."


    },
    "group_users": {
        "inv": "Ungültige Lurkers / Talkers Option.",
        "denied_1": "Nur Admins können Talkers abfragen.",
        "denied_2": "Nur Admins können Lurkers abfragen.",
        "denied_3": "Nur Admins können Lurkers zurücksetzen.",
        "denied_4": "Nur Admins können Talkers zurücksetzen.",
        "reset_1": "Lurkers zurückgesetzt",
        "reset_2": "Talkers zurückgesetzt",
        "build_1": "Activity",
        "build_2": "Mitglieder von",
        "purge_inv": "Ungültige Purge Option.",
        "purge_denied_1": "Nur Admins können den Purge Befehl verwenden.",
        "purge_message_1": "Es können nur 5 oder weniger Mitglieder auf einmal entfernt werden.",
        "purge_message_2a": "Bitte warte",
        "purge_message_2b": "Minuten vor dem erneuten löschen.",
        "purge_message_3": "Entferne Benutzer aus der Gruppe, dem Cache und der Datenbank.",
        "purge_message_4": "I can't do that! There aren't enough members left to do that with!"
    },
    "group_search": {
        "udic_inv": "Ungültige Urban Dictionary Option.",
        "udic_1": "Urban Dictionary: An",
        "udic_2": "Urban Dictionary: Aus",
        "udic_3": "Diese Funktion ist nicht verfügbar.",
        "dic_inv": "Ungültige Urban Dictionary Option.",
        "dic_1": "Dictionary: An",
        "dic_2": "Dictionary: Aus",
        "dic_3": "Diese Funktion ist nicht verfügbar.",
        "dic_4": "Entschuldigung, zu viele Treffer. Bitte grenze deine Suche weiter ein.",
        "yt_inv": "Ungültige Youtube Option.",
        "yt_1": "Youtube: An",
        "yt_2": "Youtube: Aus",
        "yt_3": "Keine Ergebnisse",
        "yt_4": "Diese Funktion ist nicht verfügbar.",
        "wiki_inv": "Ungültige Wiki Option.",
        "wiki_1": "Wiki: An",
        "wiki_2": "Wiki: Aus",
        "wiki_3": "Diese Funktion ist nicht verfügbar.",
        "wiki_4": "Entschuldigung, zu viele Treffer. Bitte grenze deine Suche weiter ein."
    },
    "group_fun": {
        "clever_inv": "Ungültige Cleverbot Option",
        "clever_1": "Cleverbot Status: On",
        "clever_2": "Cleverbot Status: Off",
        "trivia_inv": "Ungültige Trivia Option",
        "trivia_1": "Trivia läuft bereits.",
        "trivia_2": "Trivia gestartet.",
        "trivia_3": "Trivia gestoppt.",
        "trivia_4": "Trivia läuft nicht.",
        "trivia_5": "Die Zeit ist um.",
        "trivia_6": "Die Zeit ist abgelaufen, nächste Frage...",
        "trivia_7": "Nächste Frage...",
        "trivia_8": "ist richtig!",
        "trivia_9": "Punkte",
        "trivia_10": "Falsch.",
        "trivia_11": "Endergebnis",
        "confess_inv": "Ungültige Confessions Option",
        "confess_1": "sende Deine Geheimnisse PN an",
        "confess_2": "Geheimnis Ich glaube Adam ist in Ordnung!",
        "confess_3": "Confessions: An",
        "confess_4": "Confessions: Aus",
        "confess_5": "Nur Admins können Geheimnisse löschen",
        "confess_6": "Geheimnis gelöscht",
        "confess_7": "Alle Geheimnisse gelöscht",
        "confess_8": "Dies ist nichtn dein Geheimnis.",
        "confess_9": "Geheimnis nicht gefunden.",
        "confess_10": "Geheimnis von",
        "confess_11": "Geheimnisse",
        "confess_12": "Diese Funktion ist nicht verfügbar.",
        "chance_inv": "Ungültige Option",
        "chance_1": "Kopf",
        "chance_2": "Zahl",
        "chance_3": "Ich",
        "chance_4": "Du",
        "chance_5": "Lege eine Zahl fest.",
        "kdice1_1": "Sauge",
        "kdice1_2": "Blase",
        "kdice1_3": "Lecke",
        "kdice1_4": "Küsse",
        "kdice1_5": "Berühre",
        "kdice2_1": "Ohren",
        "kdice2_2": "Lippen",
        "kdice2_3": "Oberschenken",
        "kdice2_4": "Nabel",
        "kdice2_5": "Hand",
        "mball_1": "Es ist sicher.",
        "mball_2": "Scheißt ein Bär in den Wald?",
        "mball_3": "Aber sowas von",
        "mball_4": "Ja - sicherlich.",
        "mball_5": "Du kannst dich darauf verlassen.",
        "mball_6": "Ja, aber mach es völlig betrunken.",
        "mball_7": "Höchstwahrscheinlich.",
        "mball_8": "Gute Aussichten.",
        "mball_9": "Geh weg, ich bin beschäftigt.",
        "mball_10": "Die Zeichen zeigen auf Ja.",
        "mball_11": "Die Antwort verschwindet im Nebel, versuche es noch einmal.",
        "mball_12": "Frag mich später noch einmal.",
        "mball_13": "Das solltest Du noch nicht erfahren.",
        "mball_14": "Ich kann jetzt keine Vorhersage treffen.",
        "mball_15": "Konzentriere dich und frage noch einmal.",
        "mball_16": "Verlass dich nicht drauf.",
        "mball_17": "...ähhhh nein...",
        "mball_18": "Nah.",
        "mball_19": "Die Aussichten sind nicht gut.",
        "mball_20": "Ich bin skeptisch.",
        "hug_inv": "Ungültige hug Option",
        "hug_1a": "hast mal nen Euro?",
        "hug_1b": "Nein, war nur Spaß.",
        "hug_1c": "Umarmungen gibt es gratis *hug*",
        "hug_2": "klar! *hugs*",
        "hug_3": "Umarmung kommt!",
        "hug_4": "*big hug* 😀",
        "hug_5": "*hugs* 😊",
        "tag_inv": "Ungültige Tag Option",
        "tag_1": "Du hast deine Aufgabe noch nicht erfüllt. {}",
        "tag_2": "{}, hat die Aufgabe noch nicht erfüllt.",
        "tag_3a": "Es ist",
        "tag_3b": "\'s Runde jemand zu ernennen!",
        "tag_4": "Niemand gewählt!",
        "tag_5": "Du kannst dich nicht selber erlösen.",
        "tag_6": "Aufgabe erfüllt!",
        "tag_7": "Ja",
        "tag_8": "Niemand",
        "tag_9": "Nein",
        "tag_10a": "Es",
        "tag_10b": "Ernannt von",
        "tag_10c": "Minuten zuvor",
        "tag_10d": "Aufgabe erfüllt",
        "tag_11": "Tag: An",
        "tag_12": "Tag: Aus",
        "tag_13": "Anfrage fehlgeschlagen",
        "scramble_correct": " Richtig! Du gewinnst {} 🍎!",
        "scramble_incorrect": " Das war nicht richtig, versuche es noch einmal.",
        "scramble_error": "Ich konnte kein neues Wort laden.",
        "scramble_reset": "Die Lösung lautet {}. Neustart.",
        "rank_1": "Rank: An",
        "rank_2": "Rank: Aus",
        "rank_3": "Die ersten 10 Plätze: ",
        "rank_4": "Die letzten 10 Plätze: "

    },
    "group": {
        "chance_0": "Hinfort! Dämon!",
        "chance_1": "Hobots  ^=^y^d ^=^y^d",
        "chance_2": "Another one bites the dust!",
        "chance_3": "Ich seh ihre Schaltkreise!!!! Awwwwww",
        "chance_4": "Das BOOOOT  ^=  "
    },
    "feature_status": {
        "set_1a": "Aus",
        "set_1b": "An",
        "set_2": "Nice Try Rage",
        "set_3a": "kann nur ein Admin deaktivieren",
        "set_3b": "kann nur ein Admin aktivieren",
        "set_3c": "Nur Admins können {} ändern",
        "set_4a": "ist bereits aus",
        "set_4b": "ist bereits an",
        "set_msg_1": "Nachricht kann nur ein Admin einstellen",
        "set_msg_2a": "eingestellt auf",
        "set_msg_2b": "Nachricht eingestellt auf",
        "set_msg_3": "Nice try Rage",
        "cap_remove": " {} wurde von der Whitelist entfernt.",
        "set_setting_1": "Gebe nur eine Zahl an nach dem Befehl\n Beispiel: ",
        "censor_add": "Added {} to censor list.",
        "censor_remove": "{} von Zensur Liste entfernt.",
        "censor_remove_user": "Ich hab dich gewarnt..."
    },
    "group_tools": {
        "restore_missing": "Kein Backup für diese Gruppe gefunden."
    }
}
