en = {
    "group_lang": {
        "set": "English: On",
        "inv": "Invalid Language Option.",
        "message_1": "English: On",
        "message_2": "English already on.",
        "message_3": "Language can only be changed by admin."

    },
    "group_users": {
        "inv": "Invalid talkers/Lurkers Option.",
        "denied_1": "Only Admins can use {}.",
        "denied_2": "Only Admins can request talkers.",
        "denied_3": "Only Admins can request lurkers.",
        "denied_4": "Only Admins can reset lurkers.",
        "denied_5": "Only Admins can reset talkers.",
        "reset_1": "Lurkers Reset",
        "reset_2": "Talkers Reset",
        "build_1": "Activity",
        "build_2": "members of",
        "purge_inv": "Invalid Purge Option.",
        "purge_denied_1": "Only Admins can request to purge users.",
        "purge_message_1": "you can only purge 5 or less members at a time.",
        "purge_message_2a": "you must wait",
        "purge_message_2b": "minutes to purge again.",
        "purge_message_3": "Removing User From Group, Cache and Database.",
        "purge_message_4": "I can't do that! There aren't enough members left to do that with!"
    },
    "group_search": {
        "udic_inv": "Invalid Urban Dictionary Option.",
        "udic_1": "Urban Dictionary: On",
        "udic_2": "Urban Dictionary: Off",
        "udic_3": "This feature is not available.",
        "dic_inv": "Invalid Urban Dictionary Option.",
        "dic_1": "Dictionary: On",
        "dic_2": "Dictionary: Off",
        "dic_3": "This feature is not available.",
        "dic_4": "sorry too many articles found. Be more specific.",
        "yt_inv": "Invalid Youtube Option.",
        "yt_1": "Youtube: On",
        "yt_2": "Youtube: Off",
        "yt_3": "No results",
        "yt_4": "This feature is not available.",
        "wiki_inv": "Invalid Wiki Option.",
        "wiki_1": "Wiki: On",
        "wiki_2": "Wiki: Off",
        "wiki_3": "This feature is not available.",
        "wiki_4": "sorry too many articles found. Be more specific."
    },
    "group_fun": {
        "clever_inv": "Invalid Cleverbot Option",
        "clever_1": "Cleverbot Status: On",
        "clever_2": "Cleverbot Status: Off",
        "trivia_inv": "Invalid trivia Option",
        "trivia_1": "Trivia is already running.",
        "trivia_2": "Trivia started.",
        "trivia_3": "Trivia stopped.",
        "trivia_4": "Trivia is not running.",
        "trivia_5": "Time is up.",
        "trivia_6": "Time is up. Next Question...",
        "trivia_7": "Next Question...",
        "trivia_8": "is correct!",
        "trivia_9": "Scores",
        "trivia_10": "Incorrect.",
        "trivia_11": "Final Scores",
        "confess_inv": "Invalid Confessions Option",
        "confess_1": "PM your confessions to",
        "confess_2": "confession I think Adam is neat!",
        "confess_3": "Confessions: On",
        "confess_4": "Confessions: Off",
        "confess_5": "Only admins can delete confessions",
        "confess_6": "Confession Removed",
        "confess_7": "All Confessions Removed",
        "confess_8": "That is not your confession.",
        "confess_9": "Confession not found.",
        "confess_10": "Confession By",
        "confess_11": "Confessions",
        "confess_12": "This feature is not available.",
        "chance_inv": "Invalid Option",
        "chance_1": "Heads",
        "chance_2": "Tails",
        "chance_3": "me",
        "chance_4": "you",
        "chance_5": "You must specify a number.",
        "kdice1_1": "Suck",
        "kdice1_2": "Blow",
        "kdice1_3": "Lick",
        "kdice1_4": "Kiss",
        "kdice1_5": "Touch",
        "kdice2_1": "Ears",
        "kdice2_2": "Lips",
        "kdice2_3": "Thighs",
        "kdice2_4": "Navel",
        "kdice2_5": "Hand",
        "mball_1": "It is certain.",
        "mball_2": "Does a bear shit in the woods?",
        "mball_3": "Absofuckinglutley",
        "mball_4": "Yes – definitely.",
        "mball_5": "You may rely on it.",
        "mball_6": "Yes, but do it drunk as fuck.",
        "mball_7": "Most likely.",
        "mball_8": "Outlook good.",
        "mball_9": "Go away, I'm busy.",
        "mball_10": "Signs point to yes.",
        "mball_11": "Reply hazy, try again.",
        "mball_12": "Ask again later.",
        "mball_13": "Better not tell you now.",
        "mball_14": "Cannot predict now.",
        "mball_15": "Concentrate and ask again.",
        "mball_16": "Don't count on it.",
        "mball_17": "...Dude no...",
        "mball_18": "Nah.",
        "mball_19": "Outlook not so good.",
        "mball_20": "Very doubtful.",
        "hug_inv": "Invalid Hug Option",
        "hug_1a": "sure pay me 10 shmekles first",
        "hug_1b": "nah, I\'m just kidding.",
        "hug_1c": "I give hugs for free. *hugs*",
        "hug_2": "sure! *hugs*",
        "hug_3": "One hug coming right up",
        "hug_4": "*big hug* 😀",
        "hug_5": "*hugs* 😊",
        "tag_inv": "Invalid Tag Option",
        "tag_1": "You have nto completed the task. {}",
        "tag_2": "{}, has not completed their task.",
        "tag_3a": "It\'s",
        "tag_3b": "\'s turn to tag!",
        "tag_4": "Nobody is it!",
        "tag_5": "You can not free yourself.",
        "tag_6": "Paid in full!",
        "tag_7": "Yes",
        "tag_8": "Nobody",
        "tag_9": "No",
        "tag_10a": "It",
        "tag_10b": "Tagged By",
        "tag_10c": "Minutes Ago",
        "tag_10d": "Completed Task",
        "tag_11": "Tag: On",
        "tag_12": "Tag: Off",
        "tag_13": "Request failed",
        "scramble_correct": " Correct! You win {} 🍎's!",
        "scramble_incorrect": " Incorrect, try again!",
        "scramble_error": "unable to fetch new word.",
        "scramble_reset": "Word was {}. Resetting.",
        "rank_1": "Rank: On",
        "rank_2": "Rank: Off",
        "rank_3": "Top 10 Ranking: ",
        "rank_4": "Bottom 10 Ranking: "
    },
    "group": {
        "chance_0": "Be gone THOTT!",
        "chance_1": "Hobots  ^=^y^d ^=^y^d",
        "chance_2": "Another one bites the dust!",
        "chance_3": "I can see her circuits! Ewwww",
        "chance_4": "Das BOOOOT  ^=  "
    },
    "feature_status": {
        "set_1a": "Off",
        "set_1b": "On",
        "set_3a": "can only be turned off by an admin",
        "set_3b": "can only be turned on by an admin",
        "set_3c": "Only admins can modify {}.",
        "set_4a": "is already off",
        "set_4b": "is already on",
        "set_5": "not set",
        "set_msg_1": "message can only be set by an admin",
        "set_msg_2a": "set to",
        "set_msg_2b": "message set to",
        "set_setting_1": "give only a number after command\n Example: ",
        "cap_remove": "Removed {} from whitelist.",
        "censor_add": "Added {} to censor list.",
        "censor_remove": "Removed {} from censor list.",
        "censor_remove_user": "I told you not to say it..."
    },
    "group_tools": {
        "restore_missing": "No backup for this group."
    }
}
