es = {
    "group_lang": {
        "set": "Español: Activado",
        "inv": "Opción de Idioma no Válida.",
        "message_1": "Español: Activado",
        "message_2": "Español ya activado.",
        "message_3": "El idioma solo puede ser cambiado por administradores."
    },
    "group_users": {
        "inv": "Opción Inválida para Talkers/Lurkers.",
        "denied_1": "Sólo Administradores Pueden Solicitar Talkers.",
        "denied_2": "Sólo Administradores Pueden Solicitar Lurkers.",
        "denied_3": "Sólo Administradores Pueden Reiniciar Lurkers.",
        "denied_4": "Sólo Administradores Pueden Reiniciar Talkers.",
        "reset_1": "Lurkers Reiniciado",
        "reset_2": "Talkers Reiniciado",
        "build_1": "Actividad",
        "build_2": "miembros de",
        "purge_inv": "Opción Inválida para Purge.",
        "purge_denied_1": "Sólo Administradores pueden solicitar la eliminación de usuarios.",
        "purge_message_1": "Sólo puede eliminar 5 o menos miembros a la vez.",
        "purge_message_2a": "Debes esperar",
        "purge_message_2b": "Minutos para eliminar de nuevo.",
        "purge_message_3": "Eliminación del Usuario del Grupo, la Caché y la Base de Datos.",
        "purge_message_4": "¡No puedo hacerlo! ¡No quedan suficientes miembros para hacerlo!"
    },
    "group_search": {
        "udic_inv": "Opción Inválida para Diccionario Urbano.",
        "udic_1": "Diccionario Urbano: Activado",
        "udic_2": "Diccionario Urbano: Desactivado",
        "udic_3": "Esta función no está disponible.",
        "dic_inv": "Opción Inválida para Diccionario Urbano.",
        "dic_1": "Diccionario: Activado",
        "dic_2": "Diccionario: Desactivado",
        "dic_3": "Esta función no está disponible.",
        "dic_4": "Lo siento, se han encontrado demasiados artículos. Sea más específico.",
        "yt_inv": "Opción Inválida para Youtube.",
        "yt_1": "Youtube: Activado",
        "yt_2": "Youtube: Desactivado",
        "yt_3": "No hay resultados",
        "yt_4": "Esta función no está disponible.",
        "wiki_inv": "Opción Inválida para Wiki.",
        "wiki_1": "Wiki: Activado",
        "wiki_2": "Wiki: Desactivado",
        "wiki_3": "Esta función no está disponible.",
        "wiki_4": "Lo siento, se han encontrado demasiados artículos. Sea más específico."
    },
    "group_fun": {
        "clever_inv": "Opción Inválida para Cleverbot",
        "clever_1": "Estado de Cleverbot: Activado",
        "clever_2": "Estado de Cleverbot: Desactivado",
        "trivia_inv": "Opción Inválida para Trivial",
        "trivia_1": "Trivial ya está funcionando.",
        "trivia_2": "Trivial comenzó.",
        "trivia_3": "Trivial se detuvo.",
        "trivia_4": "Trivial no está funcionando.",
        "trivia_5": "Se acabó el tiempo.",
        "trivia_6": "Se acabó el tiempo. Siguiente pregunta...",
        "trivia_7": "Siguiente pregunta...",
        "trivia_8": "¡es correcto!",
        "trivia_9": "Puntuaciones",
        "trivia_10": "Incorrecto.",
        "trivia_11": "Puntuaciones finales",
        "confess_inv": "Opción Inválida para Confesiones",
        "confess_1": "Envíe un mensaje privado con sus confesiones a",
        "confess_2": "confession ¡Creo que Adam es genial!",
        "confess_3": "Confesiones: Activado",
        "confess_4": "Confesiones: Desactivado",
        "confess_5": "Sólo Administradores pueden borrar las confesiones.",
        "confess_6": "Confesión Eliminada",
        "confess_7": "Todas las confesiones eliminadas",
        "confess_8": "Esa no es tu confesión.",
        "confess_9": "Confesión no encontrada.",
        "confess_10": "Confesión de",
        "confess_11": "Confesiones",
        "confess_12": "Esta función no está disponible.",
        "chance_inv": "Opción Inválida",
        "chance_1": "Cara",
        "chance_2": "Cruz",
        "chance_3": "yo",
        "chance_4": "tú",
        "chance_5": "Debe especificar un número.",
        "kdice1_1": "Chupar",
        "kdice1_2": "Soplar",
        "kdice1_3": "Lamer",
        "kdice1_4": "Besar",
        "kdice1_5": "Tocar",
        "kdice2_1": "Orejas",
        "kdice2_2": "Labios",
        "kdice2_3": "Muslos",
        "kdice2_4": "Ombligo",
        "kdice2_5": "Mano",
        "mball_1": "Es cierto.",
        "mball_2": "¿Caga un oso en el bosque?",
        "mball_3": "Absolutamente jodido",
        "mball_4": "Sí – definitivamente.",
        "mball_5": "Puede confiar en ello.",
        "mball_6": "Sí, pero hazlo borracho como una cuba.",
        "mball_7": "Muy probablemente.",
        "mball_8": "Perspectivas buenas.",
        "mball_9": "Vete, estoy ocupad@.",
        "mball_10": "Los indicios apuntan a que sí.",
        "mball_11": "Respuesta borrosa, inténtalo de nuevo.",
        "mball_12": "Vuelve a preguntar más tarde.",
        "mball_13": "Mejor que no te lo diga ahora.",
        "mball_14": "No puedo predecirlo ahora.",
        "mball_15": "Concéntrate y vuelve a preguntar.",
        "mball_16": "No cuentes con ello.",
        "mball_17": "...Amigo no...",
        "mball_18": "Nah.",
        "mball_19": "Las perspectivas no son tan buenas.",
        "mball_20": "Muy dudos@.",
        "hug_inv": "Opción Inválida para Abrazo",
        "hug_1a": "Seguro, págame primero 10 shmekles",
        "hug_1b": "Nah, sólo estoy bromeando.",
        "hug_1c": "Doy abrazos gratis. *abrazos*",
        "hug_2": "¡Seguro! *abrazos*",
        "hug_3": "Un abrazo enseguida",
        "hug_4": "*un gran abrazo* 😀",
        "hug_5": "*abrazos* 😊",
        "tag_inv": "Opción Inválida para Reto",
        "tag_1": "No has completado la tarea. {}",
        "tag_2": "{}, no ha completado su tarea.",
        "tag_3a": "Es",
        "tag_3b": "¡es el turno de retar!",
        "tag_4": "¡No es nadie!",
        "tag_5": "No puedes liberarte a ti mismo.",
        "tag_6": "¡Pagado en su totalidad!",
        "tag_7": "Si",
        "tag_8": "Nadie",
        "tag_9": "No",
        "tag_10a": "Es",
        "tag_10b": "Retado Por",
        "tag_10c": "Minutos que lo hizo ",
        "tag_10d": "Tarea Completada",
        "tag_11": "Reto: Activado",
        "tag_12": "Reto: Desactivado",
        "tag_13": "Solicitud Fallida",
        "scramble_correct": " ¡Correcto! Has ganado {} 🍎's!",
        "scramble_incorrect": " Incorrecto, ¡Intentálo de nuevo!",
        "scramble_error": "no se puede buscar una nueva palabra.",
        "scramble_reset": "La palabra era {}. Reiniciando.",
        "rank_1": "Rank: Activado",
        "rank_2": "Rank: Desactivado",
        "rank_3": "Clasificación de los 10 primeros: ",
        "rank_4": "Clasificación de los 10 últimos: "
    },
    "group": {
        "chance_0": "¡Vete Zorra!",
        "chance_1": "Bots de Spam  ^=^y^d ^=^y^d",
        "chance_2": "¡Otr@ que muerde el polvo!",
        "chance_3": "¡Puedo ver sus circuitos! Ewwww",
        "chance_4": "Das BOOOOT  ^=  "
    },
    "feature_status": {
        "set_1a": "Desactivado",
        "set_1b": "Activado",
        "set_2": "Buen Intento Rage",
        "set_3a": "sólo puede ser desactivado por un administrador",
        "set_3b": "sólo puede ser activado por un administrador",
        "set_3c": "Sólo los administradores pueden modificar {}",
        "set_4a": "ya está desactivado",
        "set_4b": "ya está activado",
        "set_msg_1": "el mensaje sólo puede ser establecido por un administrador",
        "set_msg_2a": "configurado a",
        "set_msg_2b": "los mensajes se configuraron a",
        "set_msg_3": "Buen Intento Rage",
        "set_setting_1": "Da solo un número después del comando\n Ejemplo: ",
        "cap_remove": "Eliminado {} de la lista blanca.",
        "censor_add": "Agregado {} a la lista de censura.",
        "censor_remove": "Eliminado {} de la lista de censura.",
        "censor_remove_user": "Te dije que no lo dijeras..."
    },
    "group_tools": {
        "restore_missing": "No hay copia de seguridad para este grupo.",


    }
}
