nl = {
    "group_lang": {
        "inv": "Invalid Language Option.",
        "message_1": "English: On",
        "message_2": "English already on.",
        "message_3": "Language can only be changed by admin."
    },
    "units": {
      "hour": "hour",
      "hours": "hours",
      "minute": "minute",
      "minutes": "minutes",
      "second": "second",
      "seconds": "seconds",
      "day": "day",
      "days": "days"
    },
    "group_admins": {
        "cooldown_1a": "you must wait",
        "cooldown_1b": "minutes to use {} again.",
        "cooldown_1c": "seconds to use {} again.",
        "timer_err1": "must be less than twenty minutes.",
        "timer_err2": "already running.",
        "timer_err3": "Time needs specified: ",
        "timer_start": "started for:",
        "timer_stop": "stopped.",
        "fed_not_found": "404 Federation Not Found.",
        "fed_added1": "Added {} to federation ban.",
        "fed_added2": "{} already federation banned.",
        "fed_removed1": "Removed {} from federation ban.",
        "fed_removed2": "{} not federation banned.",
        "fed_err1": "{} can\'t be added to federation ban.",
        "fed_err2": "Group not in a federation.",
        "no_data": "No group data.",
        "gban_err1": "Unable to global ban {} user.",
        "gban_err2": "{} can\'t be added to global ban.",
        "fed_join1": "Added group to federation {}",
        "fed_join2": "{} not found.",
        "fed_join3": "Group already in a federation.",
        "fed_join4": "You must the federation owner to add a group.",
        "fed_leave1": "Removed group from federation.",
        "fed_leave2": "Group not in a federation.",
        "fed_leave3": "You must be federation owner to leave.",
        "transfer1": "Transfer Complete: \nFrom: {}\nTo: {}",
        "transfer2": "Remote Data Transfer Complete.",
        "transfer_err1": "Must be admin in source group.",
        "transfer_err2": "Must be admin in destination group.",
        "transfer_err3": "Transfer Data Corrupt.",
        "transfer_err4": "Source group not found, check for correct hash. {}",
        "transfer_err5": "Destination group not found, check for correct hash. {}",
        "transfer_err6": "Can not get your user info from source group. {}",
        "transfer_err7": "Can not get your user info from destination group. {}",
        "transfer_err8": "Can not get your user info from source group. {}",
        "backup_1": "Backup Complete",
        "restore_1": "Restore Complete",
        "forward_err1": "PM is unavailable, please open a PM with me and rejoin group.",
        "forward_err2": "Media Forward Disabled",
        "purge_message_1": "you can only purge 5 or less members at a time.",
        "purge_message_2a": "you must wait",
        "purge_message_2b": " to purge again.",
        "purge_message_3": "Removing User From Group, Cache and Database.",
        "purge_message_4": "I can't do that! There aren't enough members left to do that with!",
        "whitelist_message_1": "Added {} to whitelist.",
        "whitelist_message_2": "Removed {} from whitelist.",
        "whitelist_err_1": "Can\'t find user {}."


    },
    "group_users": {
        "inv": "Invalid Option.",
        "generic_error": "Unknown error.",
        "denied_1": "Only admins can use {}."
    },
    "group_fun": {
        "greeting_1": "Hello",
        "mball_1": "It is certain.",
        "mball_2": "Does a bear shit in the woods?",
        "mball_3": "Absofuckinglutley",
        "mball_4": "Yes – definitely.",
        "mball_5": "You may rely on it.",
        "mball_6": "Yes, but do it drunk as fuck.",
        "mball_7": "Most likely.",
        "mball_8": "Outlook good.",
        "mball_9": "Go away, I'm busy.",
        "mball_10": "Signs point to yes.",
        "mball_11": "Reply hazy, try again.",
        "mball_12": "Ask again later.",
        "mball_13": "Better not tell you now.",
        "mball_14": "Cannot predict now.",
        "mball_15": "Concentrate and ask again.",
        "mball_16": "Don't count on it.",
        "mball_17": "...Dude no...",
        "mball_18": "Nah.",
        "mball_19": "Outlook not so good.",
        "mball_20": "Very doubtful.",
        "rank_1": "Rank: On",
        "rank_2": "Rank: Off",
        "rank_3": "Top 10 Ranking: ",
        "rank_4": "Bottom 10 Ranking: ",
        "dice_err_1": "I can only roll 5 dice.",
        "dice_err_2": "You must specify a number. Between 2 and 10000",
        "scramble_correct": " Correct! You win {} 🍀's!",
        "scramble_incorrect": " Incorrect, try again!",
        "scramble_error": "unable to fetch new word.",
        "scramble_reset": "Word was {}. Resetting."
    },
    "group_status": {
        "group_name_change": "Group name changed to:",
        "promote": "Promoted",
        "demote": "Demoted"

    },
    "feature_status": {
        "set_1a": "Off",
        "set_1b": "On",
        "set_3a": "can only be turned off by an admin.",
        "set_3b": "can only be turned on by an admin.",
        "set_4a": "is already off.",
        "set_4b": "is already on.",
        "set_5": "is not set.",
        "set_msg_1": "can only be set by an admin.",
        "set_msg_2a": "set to",
        "set_setting_1": "give only a number after command\n Example: ",
        "set_setting_2": "give only a number and m or s after command\n Example: ",
        "censor_add": "Added {} to censor list.",
        "censor_remove": "Removed {} from censor list.",
        "censor_remove_user": "I told you not to say it..."
    }
}
